[package]
name = "rawsemble"
version = "0.1.0"
authors = ["Joel Denning <joeldenning@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
relative-path = "1.3.2"
